dist: xenial

language: python

python:
  - 3.6

install:
  - pip install -r requirements-dev.txt -r requirements.txt

script:
  - pycodestyle app tests
  - pylint app
  - python3 -m app init-db
  - pytest tests
