dist: xenial

language: python

python:
  - 3.6

install:
  - pip install -r requirements-dev.txt -r requirements.txt

script:
  - pycodestyle app
  - pylint app
  - python3 -m app load-db
  - pytest app/tests
