language: python

dist: bionic

python:
  - '3.6'

install:
  - pip install -r requirements-dev.txt -r requirements.txt

script:
  - pycodestyle app
  - pylint app
  - scripts/sql.sh schema && pytest
