#!/bin/sh -eu

# configure-env: open application environment in a text editor
# Copyright (C) 2018  "Michael G. Morey" <mgmorey@gmail.com>

# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.

# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.

# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <https://www.gnu.org/licenses/>.

abort() {
    printf "$@" >&2
    exit 1
}

assert() {
    "$@" || abort "%s: Assertion failed: %s\n" "$0" "$*"
}

configure_env() {
    validate_user_name "$(get_real_user)"

    if [ -z "${TERM-}" ]; then
	exit 0
    elif [ -z "${EDITOR-}" ]; then
	exit 0
    elif [ $TERM = dumb ]; then
	if [ $EDITOR != emacs ]; then
	    exit 0
	elif [ -z "${DISPLAY-}" ]; then
	    exit 0
	fi
    fi

    file="$1"
    template="$2"
    create_tmpfile

    if [ -r $file ]; then
	/bin/cp -f $file $tmpfile
    elif [ -r $template ]; then
	/bin/cp -f $template $tmpfile
    fi

    if $EDITOR $tmpfile; then
	/bin/mv -f $tmpfile $file
	chgrp $(id -g) $file
    fi
}

get_realpath() (
    assert [ $# -ge 1 ]
    realpath=$(which realpath)

    if [ -n "$realpath" ]; then
	$realpath "$@"
    else
	for file; do
	    if expr "$file" : '/.*' >/dev/null; then
		printf "%s\n" "$file"
	    else
		printf "%s\n" "$PWD/${file#./}"
	    fi
	done
    fi
)

usage_error() {
    printf "$@" >&2
    exit 2
}

if [ $# -lt 1 ]; then
    usage_error "%s: Not enough arguments\n" "$0"
elif [ $# -gt 2 ]; then
    usage_error "%s: Too many arguments\n" "$0"
fi

case "$0" in
    (*/*)
	script_dir=$(get_realpath "$(dirname "$0")")
	;;
    (*)
	script_dir=
	;;
esac

script_prefix=${script_dir:+$script_dir/}

. "${script_prefix}common-functions.sh"

configure_env "$@"
