#!/bin/sh -eu

# install-dependencies: install prerequisites for developing app
# Copyright (C) 2018  "Michael G. Morey" <mgmorey@gmail.com>

# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.

# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.

# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <https://www.gnu.org/licenses/>.

CATEGORIES="development http-client python-development python-library \
python-mysql python-package python-postgresql python-sqlalchemy \
python-sqlite python-utility"

abort() {
    printf "$@" >&2
    exit 1
}

abort_not_supported() {
    abort "%s: %s: %s not supported\n" "$script" "$PRETTY_NAME" "$*"
}

assert() {
    "$@" || abort "%s: Assertion failed: %s\n" "$script" "$*"
}

get_packages() {
    get-packages $CATEGORIES
}

get_realpath() (
    assert [ $# -ge 1 ]
    realpath=$(which realpath || true)

    if [ -n "$realpath" ]; then
        $realpath "$@"
    else
        for file; do
            if expr "$file" : '/.*' >/dev/null; then
                printf '%s\n' "$file"
            else
                printf '%s\n' "$PWD/${file#./}"
            fi
        done
    fi
)

install_dependencies() {
    validate_platform
    packages=$(get_packages)
    pattern=$(get-packages -s pattern development)

    if [ -n "$packages" ]; then
        install-packages ${pattern:+-p "$pattern" }$packages
    fi
}

usage_error() {
    printf "$@" >&2
    exit 2
}

validate_platform() {
    case "$ID" in
        (amzn)
            true
            ;;
        (centos)
            true
            ;;
        (debian|raspbian)
            true
            ;;
        (fedora)
            true
            ;;
        (opensuse-leap)
            true
            ;;
        (opensuse-tumbleweed)
            true
            ;;
        (rhel|ol)
            true
            ;;
        (ubuntu)
            true
            ;;
        (freebsd)
            true
            ;;
        (illumos)
            true
            ;;
        (macos)
            true
            ;;
        (netbsd)
            true
            ;;
        (solaris)
            true
            ;;
        (windows)
            case "$kernel_name" in
                (MINGW64_NT)
                    true
                    ;;
                (*)
                    abort_not_supported Release
                    ;;
            esac
            ;;
        (*)
            abort_not_supported "Operating system"
            ;;
    esac
}

if [ $# -gt 0 ]; then
    usage_error "%s: Too many arguments\n" "$script"
fi

script=$(basename "$0")

case "$0" in
    (*/*)
        script_dir=$(get_realpath "$(dirname "$0")")
        ;;
    (*)
        script_dir=
        ;;
esac

script_prefix=${script_dir:+$script_dir/}

. "${script_prefix}common-functions.sh"

bin_dir=$(get_bin_directory "$script_dir")
set_user_profile "$bin_dir"
eval $(get-os-release -x)
install_dependencies
